openapi: 3.0.0
info:
  title: Hymns API
  description: API for managing and retrieving hymns in different versions
  version: 1.0.0

paths:
  /hymns:
    get:
      summary: Get list of hymn titles
      tags:
        - HYMNS
      description: Retrieves a list of hymn titles with their IDs and hymn numbers
      parameters:
        - in: query
          name: version
          schema:
            type: string
            enum: [TWI, ENGLISH]
          description: Language version of the hymns
          required: false
          default: TWI
      responses:
        '200':
          description: Successfully retrieved hymn titles
          content:
            application/json:
              schema:
                type: object
                properties:
                  titles:
                    type: array
                    items:
                      type: object
                      properties:
                        hymn:
                          type: object
                          properties:
                            id:
                              type: string
                            title:
                              type: string
                            hymn_number:
                              type: integer
        '400':
          description: Invalid version provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Invalid version(twi or english)'

  /hymns/{hymnId}:
    get:
      summary: Get specific hymn details
      tags:
        - HYMNS
      description: Retrieves detailed information about a specific hymn, preferably use hymn id in url
      parameters:
        - in: path
          name: hymnId
          required: true
          schema:
            type: string
          description: The ID of the hymn to retrieve
      responses:
        '200':
          description: Successfully retrieved hymn details
          content:
            application/json:
              schema:
                type: object
                properties:
                  hymn:
                    type: object
                    properties:
                      id:
                        type: string
                      title:
                        type: string
                      hymn_number:
                        type: integer
                      lyrics:
                        type: string
        '409':
          description: Hymn not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Hymn not found'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Internal Server Error'